/* Generated by wayland-scanner 1.23.1 */

/*
 * SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
 * SPDX-License-Identifier: MulanPSL-2.0
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface kywc_toplevel_v1_interface;

static const struct wl_interface *kywc_toplevel_v1_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	&kywc_toplevel_v1_interface,
	NULL,
	&kywc_toplevel_v1_interface,
};

static const struct wl_message kywc_toplevel_manager_v1_requests[] = {
	{ "stop", "", kywc_toplevel_v1_types + 0 },
};

static const struct wl_message kywc_toplevel_manager_v1_events[] = {
	{ "toplevel", "ns", kywc_toplevel_v1_types + 4 },
	{ "finished", "", kywc_toplevel_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface kywc_toplevel_manager_v1_interface = {
	"kywc_toplevel_manager_v1", 1,
	1, kywc_toplevel_manager_v1_requests,
	2, kywc_toplevel_manager_v1_events,
};

static const struct wl_message kywc_toplevel_v1_requests[] = {
	{ "destroy", "", kywc_toplevel_v1_types + 0 },
	{ "set_maximized", "?s", kywc_toplevel_v1_types + 0 },
	{ "unset_maximized", "", kywc_toplevel_v1_types + 0 },
	{ "set_minimized", "", kywc_toplevel_v1_types + 0 },
	{ "unset_minimized", "", kywc_toplevel_v1_types + 0 },
	{ "set_fullscreen", "?s", kywc_toplevel_v1_types + 0 },
	{ "unset_fullscreen", "", kywc_toplevel_v1_types + 0 },
	{ "activate", "", kywc_toplevel_v1_types + 0 },
	{ "close", "", kywc_toplevel_v1_types + 0 },
	{ "enter_workspace", "s", kywc_toplevel_v1_types + 0 },
	{ "leave_workspace", "s", kywc_toplevel_v1_types + 0 },
	{ "move_to_workspace", "s", kywc_toplevel_v1_types + 0 },
	{ "move_to_output", "s", kywc_toplevel_v1_types + 0 },
	{ "set_position", "ii", kywc_toplevel_v1_types + 0 },
	{ "set_size", "uu", kywc_toplevel_v1_types + 0 },
};

static const struct wl_message kywc_toplevel_v1_events[] = {
	{ "closed", "", kywc_toplevel_v1_types + 0 },
	{ "done", "", kywc_toplevel_v1_types + 0 },
	{ "title", "s", kywc_toplevel_v1_types + 0 },
	{ "app_id", "s", kywc_toplevel_v1_types + 0 },
	{ "primary_output", "s", kywc_toplevel_v1_types + 0 },
	{ "workspace_enter", "s", kywc_toplevel_v1_types + 0 },
	{ "workspace_leave", "s", kywc_toplevel_v1_types + 0 },
	{ "capabilities", "u", kywc_toplevel_v1_types + 0 },
	{ "state", "u", kywc_toplevel_v1_types + 0 },
	{ "parent", "?o", kywc_toplevel_v1_types + 6 },
	{ "icon", "s", kywc_toplevel_v1_types + 0 },
	{ "geometry", "iiuu", kywc_toplevel_v1_types + 0 },
	{ "pid", "u", kywc_toplevel_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface kywc_toplevel_v1_interface = {
	"kywc_toplevel_v1", 1,
	15, kywc_toplevel_v1_requests,
	13, kywc_toplevel_v1_events,
};

