/* Generated by wayland-scanner 1.23.1 */

#ifndef KYWC_TOPLEVEL_V1_CLIENT_PROTOCOL_H
#define KYWC_TOPLEVEL_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_kywc_toplevel_v1 The kywc_toplevel_v1 protocol
 * @section page_ifaces_kywc_toplevel_v1 Interfaces
 * - @subpage page_iface_kywc_toplevel_manager_v1 - list and control toplevels
 * - @subpage page_iface_kywc_toplevel_v1 - a mapped toplevel
 * @section page_copyright_kywc_toplevel_v1 Copyright
 * <pre>
 *
 * SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
 * SPDX-License-Identifier: MulanPSL-2.0
 * </pre>
 */
struct kywc_toplevel_manager_v1;
struct kywc_toplevel_v1;

#ifndef KYWC_TOPLEVEL_MANAGER_V1_INTERFACE
#define KYWC_TOPLEVEL_MANAGER_V1_INTERFACE
/**
 * @page page_iface_kywc_toplevel_manager_v1 kywc_toplevel_manager_v1
 * @section page_iface_kywc_toplevel_manager_v1_desc Description
 *
 * A toplevel is defined as a surface with a role similar to xdg_toplevel.
 * XWayland surfaces may be treated like toplevels in this protocol.
 *
 * After a client binds the global, each mapped toplevel window will be sent
 * using the toplevel event.
 * @section page_iface_kywc_toplevel_manager_v1_api API
 * See @ref iface_kywc_toplevel_manager_v1.
 */
/**
 * @defgroup iface_kywc_toplevel_manager_v1 The kywc_toplevel_manager_v1 interface
 *
 * A toplevel is defined as a surface with a role similar to xdg_toplevel.
 * XWayland surfaces may be treated like toplevels in this protocol.
 *
 * After a client binds the global, each mapped toplevel window will be sent
 * using the toplevel event.
 */
extern const struct wl_interface kywc_toplevel_manager_v1_interface;
#endif
#ifndef KYWC_TOPLEVEL_V1_INTERFACE
#define KYWC_TOPLEVEL_V1_INTERFACE
/**
 * @page page_iface_kywc_toplevel_v1 kywc_toplevel_v1
 * @section page_iface_kywc_toplevel_v1_desc Description
 *
 * A kywc_toplevel_v1 object represents a mapped toplevel window.
 * A single app may have multiple mapped toplevels.
 * @section page_iface_kywc_toplevel_v1_api API
 * See @ref iface_kywc_toplevel_v1.
 */
/**
 * @defgroup iface_kywc_toplevel_v1 The kywc_toplevel_v1 interface
 *
 * A kywc_toplevel_v1 object represents a mapped toplevel window.
 * A single app may have multiple mapped toplevels.
 */
extern const struct wl_interface kywc_toplevel_v1_interface;
#endif

/**
 * @ingroup iface_kywc_toplevel_manager_v1
 * @struct kywc_toplevel_manager_v1_listener
 */
struct kywc_toplevel_manager_v1_listener {
	/**
	 * a toplevel has been created
	 *
	 * This event is emitted whenever a new toplevel window is
	 * created. It is emitted for all toplevels, regardless of the app
	 * that has created them.
	 *
	 * All initial properties of the toplevel (identifier, title,
	 * app_id) will be sent immediately after this event using the
	 * corresponding events for kywc_toplevel. The compositor will use
	 * the done event to indicate when all data has been sent.
	 * @param uuid unique id of the toplevel
	 */
	void (*toplevel)(void *data,
			 struct kywc_toplevel_manager_v1 *kywc_toplevel_manager_v1,
			 struct kywc_toplevel_v1 *toplevel,
			 const char *uuid);
	/**
	 * the compositor has finished with the toplevel manager
	 *
	 * This event indicates that the compositor is done sending
	 * events to this object. The client should destroy the object. See
	 * destroy for more information.
	 *
	 * The compositor must not send any more toplevel events after this
	 * event.
	 */
	void (*finished)(void *data,
			 struct kywc_toplevel_manager_v1 *kywc_toplevel_manager_v1);
};

/**
 * @ingroup iface_kywc_toplevel_manager_v1
 */
static inline int
kywc_toplevel_manager_v1_add_listener(struct kywc_toplevel_manager_v1 *kywc_toplevel_manager_v1,
				      const struct kywc_toplevel_manager_v1_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) kywc_toplevel_manager_v1,
				     (void (**)(void)) listener, data);
}

#define KYWC_TOPLEVEL_MANAGER_V1_STOP 0

/**
 * @ingroup iface_kywc_toplevel_manager_v1
 */
#define KYWC_TOPLEVEL_MANAGER_V1_TOPLEVEL_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_manager_v1
 */
#define KYWC_TOPLEVEL_MANAGER_V1_FINISHED_SINCE_VERSION 1

/**
 * @ingroup iface_kywc_toplevel_manager_v1
 */
#define KYWC_TOPLEVEL_MANAGER_V1_STOP_SINCE_VERSION 1

/** @ingroup iface_kywc_toplevel_manager_v1 */
static inline void
kywc_toplevel_manager_v1_set_user_data(struct kywc_toplevel_manager_v1 *kywc_toplevel_manager_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) kywc_toplevel_manager_v1, user_data);
}

/** @ingroup iface_kywc_toplevel_manager_v1 */
static inline void *
kywc_toplevel_manager_v1_get_user_data(struct kywc_toplevel_manager_v1 *kywc_toplevel_manager_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) kywc_toplevel_manager_v1);
}

static inline uint32_t
kywc_toplevel_manager_v1_get_version(struct kywc_toplevel_manager_v1 *kywc_toplevel_manager_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_manager_v1);
}

/** @ingroup iface_kywc_toplevel_manager_v1 */
static inline void
kywc_toplevel_manager_v1_destroy(struct kywc_toplevel_manager_v1 *kywc_toplevel_manager_v1)
{
	wl_proxy_destroy((struct wl_proxy *) kywc_toplevel_manager_v1);
}

/**
 * @ingroup iface_kywc_toplevel_manager_v1
 *
 * This request indicates that the client no longer wishes to receive
 * events for new toplevels.
 *
 * The Wayland protocol is asynchronous, meaning the compositor may send
 * further toplevel events until the stop request is processed.
 * The client should wait for a finished event before destroying this object.
 */
static inline void
kywc_toplevel_manager_v1_stop(struct kywc_toplevel_manager_v1 *kywc_toplevel_manager_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_toplevel_manager_v1,
			 KYWC_TOPLEVEL_MANAGER_V1_STOP, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_manager_v1), 0);
}

#ifndef KYWC_TOPLEVEL_V1_CAPABILITY_ENUM
#define KYWC_TOPLEVEL_V1_CAPABILITY_ENUM
/**
 * @ingroup iface_kywc_toplevel_v1
 * describes capabilities of the toplevel
 *
 * Describes what capabilities this toplevel has.
 */
enum kywc_toplevel_v1_capability {
	/**
	 * if this toplevel not be listed in the taskbar
	 */
	KYWC_TOPLEVEL_V1_CAPABILITY_SKIP_TASKBAR = 1,
	/**
	 * if this toplevel not appear in a switcher
	 */
	KYWC_TOPLEVEL_V1_CAPABILITY_SKIP_SWITCHER = 2,
};
#endif /* KYWC_TOPLEVEL_V1_CAPABILITY_ENUM */

#ifndef KYWC_TOPLEVEL_V1_STATE_ENUM
#define KYWC_TOPLEVEL_V1_STATE_ENUM
/**
 * @ingroup iface_kywc_toplevel_v1
 * types of states on the toplevel
 *
 * The different states that a toplevel can have.
 */
enum kywc_toplevel_v1_state {
	/**
	 * the toplevel is maximized
	 */
	KYWC_TOPLEVEL_V1_STATE_MAXIMIZED = 1,
	/**
	 * the toplevel is minimized
	 */
	KYWC_TOPLEVEL_V1_STATE_MINIMIZED = 2,
	/**
	 * the toplevel is active
	 */
	KYWC_TOPLEVEL_V1_STATE_ACTIVATED = 4,
	/**
	 * the toplevel is fullscreen
	 */
	KYWC_TOPLEVEL_V1_STATE_FULLSCREEN = 8,
};
#endif /* KYWC_TOPLEVEL_V1_STATE_ENUM */

/**
 * @ingroup iface_kywc_toplevel_v1
 * @struct kywc_toplevel_v1_listener
 */
struct kywc_toplevel_v1_listener {
	/**
	 * the toplevel has been closed
	 *
	 * The server will emit no further events on the kywc_toplevel_v1
	 * after this event. Any requests received aside from the destroy
	 * request must be ignored. Upon receiving this event, the client
	 * should destroy the handle.
	 */
	void (*closed)(void *data,
		       struct kywc_toplevel_v1 *kywc_toplevel_v1);
	/**
	 * all information about the toplevel has been sent
	 *
	 * This event is sent after all changes in the toplevel state
	 * have been sent.
	 */
	void (*done)(void *data,
		     struct kywc_toplevel_v1 *kywc_toplevel_v1);
	/**
	 * title change
	 *
	 * The title of the toplevel has changed.
	 */
	void (*title)(void *data,
		      struct kywc_toplevel_v1 *kywc_toplevel_v1,
		      const char *title);
	/**
	 * app_id change
	 *
	 * The app id of the topleve.done for details.
	 */
	void (*app_id)(void *data,
		       struct kywc_toplevel_v1 *kywc_toplevel_v1,
		       const char *app_id);
	/**
	 * toplevel's primary output changes
	 *
	 * This event is emitted whenever the output that the largest
	 * area of this toplevel is displayed on has changed.
	 * @param output the output unique id
	 */
	void (*primary_output)(void *data,
			       struct kywc_toplevel_v1 *kywc_toplevel_v1,
			       const char *output);
	/**
	 * toplevel entered a workspace
	 *
	 * This event is emitted whenever the toplevel becomes visible on
	 * the given workspace. A toplevel may be visible on multiple
	 * workspaces.
	 * @param workspace the workspace unique id
	 */
	void (*workspace_enter)(void *data,
				struct kywc_toplevel_v1 *kywc_toplevel_v1,
				const char *workspace);
	/**
	 * toplevel left a workspace
	 *
	 * This event is emitted whenever the toplevel stops being
	 * visible on the given workspace. It is guaranteed that an
	 * entered-workspace event with the same workspace has been emitted
	 * before this event.
	 * @param workspace the workspace unique id
	 */
	void (*workspace_leave)(void *data,
				struct kywc_toplevel_v1 *kywc_toplevel_v1,
				const char *workspace);
	/**
	 * capability flags
	 *
	 * What capabilities this toplevel has, sent on startup before
	 * the first done event.
	 */
	void (*capabilities)(void *data,
			     struct kywc_toplevel_v1 *kywc_toplevel_v1,
			     uint32_t flags);
	/**
	 * the toplevel state changed
	 *
	 * This event is emitted immediately after the kywc_toplevel_v1
	 * is created and each time the toplevel state changes, either
	 * because of a compositor action or because of a request in this
	 * protocol.
	 */
	void (*state)(void *data,
		      struct kywc_toplevel_v1 *kywc_toplevel_v1,
		      uint32_t state);
	/**
	 * parent change
	 *
	 * This event is emitted whenever the parent of the toplevel
	 * changes.
	 *
	 * No event is emitted when the parent handle is destroyed by the
	 * client.
	 */
	void (*parent)(void *data,
		       struct kywc_toplevel_v1 *kywc_toplevel_v1,
		       struct kywc_toplevel_v1 *parent);
	/**
	 * toplevel's icon changed
	 *
	 * This event will be sent whenever the icon changes. May be
	 * null.
	 * @param name the new icon name
	 */
	void (*icon)(void *data,
		     struct kywc_toplevel_v1 *kywc_toplevel_v1,
		     const char *name);
	/**
	 * The geometry of this toplevel in absolute coordinates
	 *
	 * This event will be sent whenever the toplevel geometry
	 * changes.
	 * @param x x position of the toplevel
	 * @param y y position of the toplevel
	 * @param width width of the toplevel
	 * @param height height of the toplevel
	 */
	void (*geometry)(void *data,
			 struct kywc_toplevel_v1 *kywc_toplevel_v1,
			 int32_t x,
			 int32_t y,
			 uint32_t width,
			 uint32_t height);
	/**
	 * process id of application owning the window
	 *
	 * This event will only be emitted once, before the first "done"
	 * event occurs.
	 * @param pid process id
	 */
	void (*pid)(void *data,
		    struct kywc_toplevel_v1 *kywc_toplevel_v1,
		    uint32_t pid);
};

/**
 * @ingroup iface_kywc_toplevel_v1
 */
static inline int
kywc_toplevel_v1_add_listener(struct kywc_toplevel_v1 *kywc_toplevel_v1,
			      const struct kywc_toplevel_v1_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) kywc_toplevel_v1,
				     (void (**)(void)) listener, data);
}

#define KYWC_TOPLEVEL_V1_DESTROY 0
#define KYWC_TOPLEVEL_V1_SET_MAXIMIZED 1
#define KYWC_TOPLEVEL_V1_UNSET_MAXIMIZED 2
#define KYWC_TOPLEVEL_V1_SET_MINIMIZED 3
#define KYWC_TOPLEVEL_V1_UNSET_MINIMIZED 4
#define KYWC_TOPLEVEL_V1_SET_FULLSCREEN 5
#define KYWC_TOPLEVEL_V1_UNSET_FULLSCREEN 6
#define KYWC_TOPLEVEL_V1_ACTIVATE 7
#define KYWC_TOPLEVEL_V1_CLOSE 8
#define KYWC_TOPLEVEL_V1_ENTER_WORKSPACE 9
#define KYWC_TOPLEVEL_V1_LEAVE_WORKSPACE 10
#define KYWC_TOPLEVEL_V1_MOVE_TO_WORKSPACE 11
#define KYWC_TOPLEVEL_V1_MOVE_TO_OUTPUT 12
#define KYWC_TOPLEVEL_V1_SET_POSITION 13
#define KYWC_TOPLEVEL_V1_SET_SIZE 14

/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_CLOSED_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_DONE_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_TITLE_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_APP_ID_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_PRIMARY_OUTPUT_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_WORKSPACE_ENTER_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_WORKSPACE_LEAVE_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_CAPABILITIES_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_STATE_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_PARENT_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_ICON_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_GEOMETRY_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_PID_SINCE_VERSION 1

/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_SET_MAXIMIZED_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_UNSET_MAXIMIZED_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_SET_MINIMIZED_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_UNSET_MINIMIZED_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_SET_FULLSCREEN_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_UNSET_FULLSCREEN_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_ACTIVATE_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_CLOSE_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_ENTER_WORKSPACE_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_LEAVE_WORKSPACE_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_MOVE_TO_WORKSPACE_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_MOVE_TO_OUTPUT_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_SET_POSITION_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_toplevel_v1
 */
#define KYWC_TOPLEVEL_V1_SET_SIZE_SINCE_VERSION 1

/** @ingroup iface_kywc_toplevel_v1 */
static inline void
kywc_toplevel_v1_set_user_data(struct kywc_toplevel_v1 *kywc_toplevel_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) kywc_toplevel_v1, user_data);
}

/** @ingroup iface_kywc_toplevel_v1 */
static inline void *
kywc_toplevel_v1_get_user_data(struct kywc_toplevel_v1 *kywc_toplevel_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) kywc_toplevel_v1);
}

static inline uint32_t
kywc_toplevel_v1_get_version(struct kywc_toplevel_v1 *kywc_toplevel_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_v1);
}

/**
 * @ingroup iface_kywc_toplevel_v1
 *
 * This request should be used when the client will no longer use the toplevel 
 * or after the closed event has been received to allow destruction of the object.
 */
static inline void
kywc_toplevel_v1_destroy(struct kywc_toplevel_v1 *kywc_toplevel_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_toplevel_v1,
			 KYWC_TOPLEVEL_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_kywc_toplevel_v1
 *
 * Requests that the toplevel be maximized. If the maximized state actually
 * changes, this will be indicated by the state event.
 */
static inline void
kywc_toplevel_v1_set_maximized(struct kywc_toplevel_v1 *kywc_toplevel_v1, const char *output)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_toplevel_v1,
			 KYWC_TOPLEVEL_V1_SET_MAXIMIZED, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_v1), 0, output);
}

/**
 * @ingroup iface_kywc_toplevel_v1
 *
 * Requests that the toplevel be unmaximized. If the maximized state actually
 * changes, this will be indicated by the state event.
 */
static inline void
kywc_toplevel_v1_unset_maximized(struct kywc_toplevel_v1 *kywc_toplevel_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_toplevel_v1,
			 KYWC_TOPLEVEL_V1_UNSET_MAXIMIZED, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_v1), 0);
}

/**
 * @ingroup iface_kywc_toplevel_v1
 *
 * Requests that the toplevel be minimized. If the minimized state actually
 * changes, this will be indicated by the state event.
 */
static inline void
kywc_toplevel_v1_set_minimized(struct kywc_toplevel_v1 *kywc_toplevel_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_toplevel_v1,
			 KYWC_TOPLEVEL_V1_SET_MINIMIZED, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_v1), 0);
}

/**
 * @ingroup iface_kywc_toplevel_v1
 *
 * Requests that the toplevel be unminimized. If the minimized state actually
 * changes, this will be indicated by the state event.
 */
static inline void
kywc_toplevel_v1_unset_minimized(struct kywc_toplevel_v1 *kywc_toplevel_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_toplevel_v1,
			 KYWC_TOPLEVEL_V1_UNSET_MINIMIZED, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_v1), 0);
}

/**
 * @ingroup iface_kywc_toplevel_v1
 *
 * Requests that the toplevel be fullscreened on the given output. If the
 * fullscreen state and/or the outputs the toplevel is visible on actually
 * change, this will be indicated by the state and output_enter/leave
 * events.
 *
 * The output parameter is only a hint to the compositor. Also, if output
 * is NULL, the compositor should decide which output the toplevel will be
 * fullscreened on, if at all.
 */
static inline void
kywc_toplevel_v1_set_fullscreen(struct kywc_toplevel_v1 *kywc_toplevel_v1, const char *output)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_toplevel_v1,
			 KYWC_TOPLEVEL_V1_SET_FULLSCREEN, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_v1), 0, output);
}

/**
 * @ingroup iface_kywc_toplevel_v1
 *
 * Requests that the toplevel be unfullscreened. If the fullscreen state
 * actually changes, this will be indicated by the state event.
 */
static inline void
kywc_toplevel_v1_unset_fullscreen(struct kywc_toplevel_v1 *kywc_toplevel_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_toplevel_v1,
			 KYWC_TOPLEVEL_V1_UNSET_FULLSCREEN, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_v1), 0);
}

/**
 * @ingroup iface_kywc_toplevel_v1
 *
 * Request that this toplevel be activated.
 * There is no guarantee the toplevel will be actually activated.
 */
static inline void
kywc_toplevel_v1_activate(struct kywc_toplevel_v1 *kywc_toplevel_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_toplevel_v1,
			 KYWC_TOPLEVEL_V1_ACTIVATE, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_v1), 0);
}

/**
 * @ingroup iface_kywc_toplevel_v1
 *
 * Send a request to the toplevel to close itself. The compositor would
 * typically use a shell-specific method to carry out this request, for
 * example by sending the xdg_toplevel.close event. However, this gives
 * no guarantees the toplevel will actually be destroyed. If and when
 * this happens, the closed event will be emitted.
 */
static inline void
kywc_toplevel_v1_close(struct kywc_toplevel_v1 *kywc_toplevel_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_toplevel_v1,
			 KYWC_TOPLEVEL_V1_CLOSE, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_v1), 0);
}

/**
 * @ingroup iface_kywc_toplevel_v1
 *
 * Make the toplevel enter a workspace. A toplevel can enter more
 * than one workspace. if the id is empty or invalid, no action will be performed.
 */
static inline void
kywc_toplevel_v1_enter_workspace(struct kywc_toplevel_v1 *kywc_toplevel_v1, const char *id)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_toplevel_v1,
			 KYWC_TOPLEVEL_V1_ENTER_WORKSPACE, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_v1), 0, id);
}

/**
 * @ingroup iface_kywc_toplevel_v1
 *
 * Make the toplevel exit a workspace.
 */
static inline void
kywc_toplevel_v1_leave_workspace(struct kywc_toplevel_v1 *kywc_toplevel_v1, const char *id)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_toplevel_v1,
			 KYWC_TOPLEVEL_V1_LEAVE_WORKSPACE, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_v1), 0, id);
}

/**
 * @ingroup iface_kywc_toplevel_v1
 *
 * Requests this toplevel to be displayed only in a specific workspace.
 */
static inline void
kywc_toplevel_v1_move_to_workspace(struct kywc_toplevel_v1 *kywc_toplevel_v1, const char *id)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_toplevel_v1,
			 KYWC_TOPLEVEL_V1_MOVE_TO_WORKSPACE, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_v1), 0, id);
}

/**
 * @ingroup iface_kywc_toplevel_v1
 *
 * Requests this toplevel to be displayed in a specific output.
 */
static inline void
kywc_toplevel_v1_move_to_output(struct kywc_toplevel_v1 *kywc_toplevel_v1, const char *id)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_toplevel_v1,
			 KYWC_TOPLEVEL_V1_MOVE_TO_OUTPUT, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_v1), 0, id);
}

/**
 * @ingroup iface_kywc_toplevel_v1
 *
 * Move the window to new coordinates.
 */
static inline void
kywc_toplevel_v1_set_position(struct kywc_toplevel_v1 *kywc_toplevel_v1, int32_t x, int32_t y)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_toplevel_v1,
			 KYWC_TOPLEVEL_V1_SET_POSITION, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_v1), 0, x, y);
}

/**
 * @ingroup iface_kywc_toplevel_v1
 *
 * Set the window to new size.
 *
 * Window size will be consider compositor window size limits.
 */
static inline void
kywc_toplevel_v1_set_size(struct kywc_toplevel_v1 *kywc_toplevel_v1, uint32_t width, uint32_t height)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_toplevel_v1,
			 KYWC_TOPLEVEL_V1_SET_SIZE, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_toplevel_v1), 0, width, height);
}

#ifdef  __cplusplus
}
#endif

#endif
